### ISSUE TITLE
Remove prototype functions

### ISSUE THREAD

**Issue by jasonmit** [Netflix/ember-nf-graph#8] opened 2015-03-30 16:44 UTC
Using Ember's prototype functions make this hard to consume for those who `EXTEND_PROTOTYPES = false`

**Comment by blesh** [comment] 2015-03-31 00:23
This is *really* good feedback. I hadn't thought about this being an issue for consumers of the add-on.

This is a pretty tall order, since I'm using `function() { }.property()` basically everywhere.  I'm happy to accept a PR on this, but for now I can't justify the effort. Likewise, since this would be such a sweeping change, it would probably be best to shore up the unit tests before undertaking this.

Closing for now, because (at least for now) I can't/won't fix this, at least in the short term.

**Comment by chnn** [comment] 2015-03-31 00:49
@blesh [ember-watson](https://github.com/abuiles/ember-watson) now includes a command to switch to the non-proto extension style that may make it easier (not manual work).

**Comment by blesh** [comment] 2015-03-31 01:06
:+1: thanks @chnn, I'll investigate this as soon as I can.

**Comment by blesh** [comment] 2015-04-10 22:46
Thank you, @jayphelps!

**Comment by jayphelps** [comment] 2015-04-10 22:47
![You're welcome](http://38.media.tumblr.com/fb98526d9830f2abe15a48b083bffaf1/tumblr_n8a6s7lofb1sr7oyro1_500.gif)

**Comment by blesh** [comment] 2015-04-11 00:20
I need to reopen this. Apparently removing prototype functions breaks using *ordinary arrays* in `{{#each}}` within Ember. All arrays used in `{{#each}}` need to be identified and wrapped with `Ember.A()` ... which smells, but ¯\_(ツ)_/¯

Unfortunately, it also means the published beta.4 is totally busted if the user doesn't disable or remove that addon. 😕

```js
Ember.A(['W','H','Y','?','!']);
```

**Comment by blesh** [comment] 2015-04-11 00:20
Really the problem is Issue #1 .... That's the CORE of all problems.

**Closed** 2015-04-13 18:54 UTC
Labels: enhancement
