### ISSUE TITLE
Remove nf-scroll-area

### ISSUE THREAD

**Issue by jayphelps** [Netflix/ember-nf-graph#43] opened 2015-04-22 21:23 UTC
~~[MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) is currently being used in [nf-scroll-area](https://github.com/Netflix/ember-nf-graph/blob/4ae80a734db28e1ae4395f86f9d100a037eba019/app/components/nf-scroll-area.js#L74) which prevents it from being used in IE 10 and below as well as phantomjs 1.x; which means testing is a pain, need to add polyfills just for testing which introduces possible bugs if the polyfill doesn't behave exactly the same.~~

`{{nf-scroll-area}}` needs to be removed from this library.

**Comment by blesh** [comment] 2015-04-22 23:05
nf-scroll-area is a remnant of splitting nf-graph from nf-table, and should be removed completely.

**Comment by blesh** [comment] 2015-04-22 23:13
duplicate of #44

**Closed by blesh** 2015-04-22 23:13 UTC

**Comment by jayphelps** [comment] 2015-04-22 23:15
@blesh technically, #44 is a duplicate of this. :yum:

**Comment by blesh** [comment] 2015-04-22 23:34
@jayphelps technically... FISTICUFFS!!!

![Fisticuffs](http://i.imgur.com/3f2VG.gif)
